import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { Box, Heading } from '@chakra-ui/react'
import HomePage from '../components/HomePage'
import axios from 'axios'

const inter = Inter({ subsets: ['latin'] })

export default function Home({homeData}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomePage {...homeData} />
      </main>
    </>
  )
}

export async function getStaticProps() {

  
  const uName = 'atuls2060'
  const url = `https://api.github.com/users/${uName}`
  const res = await axios.get(url)
  const data = await res.data

  return {
      props: {
          homeData: data
      }
  }
}
